hourly_data:
  cron: "0 * * * *"
  class: HourlyData
  queue: immediate
  args: 
  description: "Queues up the initializers for all hourly data tasks."

  cron: "30 0 * * *"
  class: CacheWarmer
  queue: immediate
  args:
  description: "Queues up cache-warming jobs."